pull_request_rules:
  - name: auto merge bump
    conditions:
      - and:
          - title~=^Bump [0-9]{8}-[0-9]+
          - author=github-actions[bot]
          - label=auto_bump
          - label=github_actions
          # - check-success=flake check
    actions:
      update:
      merge:
        method: squash
